inherit_from:
 - .rubocop_todo.yml
 - .rubocop_cocoapods.yml

#- Core -----------------------------------------------------------------------

AllCops:
  TargetRubyVersion: 2.6
  # RuboCop has a bunch of cops enabled by default. This setting tells RuboCop
  # to ignore them, so only the ones explicitly set in this file are enabled.
  DisabledByDefault: true
  SuggestExtensions: false
  Exclude:
    - spec/fixtures/**/*
    - vendor/bundle/**/*
    - lib/cocoapods-core/vendor/**/*

Naming/FileName:
  Exclude:
    - lib/cocoapods-core.rb

Style/TrivialAccessors:
  Exclude:
    - lib/cocoapods-core/*/dsl.rb
    - lib/cocoapods-core/*/dsl/*
